from typing import Protocol, Iterable

from src.domains import Recipe, IngredientMatch


class RepositoryProtocol(Protocol):
    def initialize(self) -> None: ...

    def bulk_insert_recipes(self, recipes: Iterable[Recipe]) -> int: ...
    def build_ingredient_matches(self) -> int: ...

    def get_ingredient_matches(
        self, ingredient: str, top_n: int
    ) -> list[IngredientMatch]: ...
    def search_recipes_by_ingredients(self, ingredients: list[str]) -> list[Recipe]: ...
    def search_recipes_by_title(self, title: str) -> list[Recipe]: ...

    def close(self) -> None: ...
